### PR TITLE
Add missing jars to fix class not found error

### PR DESCRIPTION
**Pull request by shenie**
This fixes https://github.com/awslabs/amazon-kinesis-client-nodejs/issues/344

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by shenie** [comment]
@lucienlu-aws would you be able to have a look at this PR please?

**Comment by lucienlu-aws** [comment]
Thanks for catching this, just made a minor change to fix the spacing.

**Review by lucienlu-aws — APPROVED** [review]

**Comment by shenie** [comment]
Thanks for merging the PR, could we please get the fix released as well.

**Comment by lucienlu-aws** [comment]
We'll work on getting the release out for this fix

**Comment by vincentbranchet** [comment]
Hello, gently bumping this thread since we are still waiting for the upcoming release

**Comment by stekycz** [comment]
Hi, I am really looking forward to see this fix getting released. Thanks!

**Pull request merged**
